### ISSUE TITLE
Twitter username suggestion

### ISSUE THREAD

**Issue by dev-bre** [linvi/tweetinvi#1024]
Is it possible to receive suggestions when starting to type a Twitter username?

Something similar to how Twitter does when starting a string with the @ ?

**Comment by linvi** [comment]
I am not aware of such functionality but you could you use SearchUsers and use a caching mechanism to help you with RateLimits.

**Comment by jdahan91** [comment]
I have written something like this in one of my mobile apps, what you're doing is handling the TextChanged event and call one of Tweetinvi's api SearchAsync.SearchUsers() within the handler and then use a AutoComplete text view and bind the result to it.

**Comment by dev-bre** [comment]
Good suggestion, even though if you hit the Twitter API on every single event you will reach the rate limit pretty quickly.

Would be nice if Tweetinvy could expose a working example of how to implement this scenario which I reckon is very common being a Twitter API.

**Comment by linvi** [comment]
> Would be nice if Tweetinvi could expose a working example of how to implement this scenario which I reckon is very common being a Twitter API.

I have decided a long time ago to stop supporting customer based scenario because they require extra work (and I don't even have enough time to support all the api endpoints) but also because they are very strongly opinionated.

For example this feature can use a in memory cache, no cache, redis cache, aspnet cache...
Everybody has different need and has to use the right tools for it, I find it best to advise people when they have such questions.

Cheers,
Linvi

**Comment by jdahan91** [comment]
I have to agree with linvi on this. Linvi is providing you a framework to work with and you have to design the algorithm yourself limited by the apis available.

Adding custom based functionality is pointless because it defeats the whole purpose of giving you freedom to program the sdk.

**Comment by dev-bre** [comment]
Absolutely. It would have been a nice to have, but I wasn't expecting it at all.

I think this issue can be closed.
