### ISSUE TITLE
[question] GetUsersFromIds progress

### ISSUE THREAD

**Issue by KakCAT** [linvi/tweetinvi#1042]
Hi!  Is there any way to get any kind of progress for the function GetUsersFromIds ?
Upload media seems to have a progress callback, but GetUsersFromIds can take a long time and (apparently) has no way to get a way to know its progress.

Thanks!

**Comment by linvi** [comment]
Hello there,

Effectively this is a limitation of Tweetinvi 4.0.
In 5.0, `GetUsers` is now limited as per Twitter limits so that only 1 request is being performed.

You will have to manually execute multiple `client.Users.GetUsersAsync()` and you will get control over the when the operations will be completed.

**Comment by KakCAT** [comment]
thanks for the answer!
