### ISSUE TITLE
Trends are not refreshing

### ISSUE THREAD

**Issue by jonathanfavorite** [linvi/tweetinvi#1062]
``` c#
selectedWoed = Convert.ToInt32("23424977"); //usa
var getSelectedWoed = Trends.GetTrendsAt(selectedWoed);

var firstInsideNode = getSelectedWoed.Trends.ToList();

for(int i = 0; i <= firstInsideNode.Count - 1; i++)
{
    listBox2.Items.Add(firstInsideNode[i].Name);
}
```

using the code above, I am trying to get the newest trends in the USA. The list seemed to have last updated on Monday, as the top trend in the US was the first day of the RNC.

Is there a cache issue or is something wrong with the API?

thanks.

**Comment by linvi** [comment]
Tweetinvi does not have any cache, Twitter probably does though.

I suggest you ask this type of question to twittercommunity.com.
Please add a tweetinvi keyword and add a link to the question here there so that I can track the answer and help new developers coming with the same question.

Cheers,
Linvi
