### ISSUE TITLE
Replying to a reply does not reply. Instead it does create a normal tweet 

### ISSUE THREAD

**Issue by janniksam** [linvi/tweetinvi#1072]
Any idea, why this will not work?
```cs
public async Task<bool> ReplyAsync(long tweetId, string replyMessage)
{
    var tweetsToReplyTo = await _twitterClient.Tweets.GetTweetsAsync(new[] {tweetId}).ConfigureAwait(false);
    var tweetToReplyTo = tweetsToReplyTo?.FirstOrDefault();
    if (tweetToReplyTo == null)
    {
        return false;
    }

    await _twitterClient.Tweets.PublishTweetAsync(new PublishTweetParameters(replyMessage)
    {
        InReplyToTweet = tweetToReplyTo
    }).ConfigureAwait(false);
    return true;
}
```

Instead of replying to existing tweets it just creates a normal tweets. Do I lack some info?
The `tweetId` passed is fine, it does give me a tweet and it does not return false..

**Comment by linvi** [comment]
Hello there,

So the problem comes from the fact that you need to have an `@<username>` at the start of a reply now. This has been a change on the Twitter API side.

Here is how a code could look like :

``` c#
var tweet = await userClient.Tweets.GetTweetAsync(1315345368717066240);
var reply = await userClient.Tweets.PublishTweetAsync(new PublishTweetParameters($"@{tweet.CreatedBy} Reply to 1315345368717066240")
{
    InReplyToTweet = tweet
});
```

Twitter no longer authorises to create a reply without the `@username` so you will need to get the tweet before being able to send a reply.

I will update the documentation to reflect this.

**Comment by linvi** [comment]
Documentation updated.
