### ISSUE TITLE
Getting the latest tweet of a user

### ISSUE THREAD

**Issue by AlexGipp** [linvi/tweetinvi#1082]
How would i get the latest tweet of a specific user?

Im asking this because appereantly the endpoint:
https://api.twitter.com/1.1/statuses/user_timeline.json?user_id=12345678

doesnt always return the latest tweet.
(https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/guides/working-with-timelines) (The max_id parameter)

**Comment by linvi** [comment]
Hello there.

My understanding is that you have a problem with retrieving the latest tweets published by a specific user.
As mentioned in the article you pointed towards, you should not use the `MaxId` parameter or the `SinceId` parameter.
When both of these property are set to `null` you should receive the latest tweets. This logic is actually tested in Tweetinvi End to End tests.

If you are actually experiencing this issue at the moment, I would suggest communicating with Twitter about it on https://twittercommunity.com/ and sharing a link to your question here so that I can follow up on it.

Cheers,
Linvi

**Comment by AlexGipp** [comment]
Ah okay, it works. THanks for your help
