### ISSUE TITLE
Get Popular tweets in new version

### ISSUE THREAD

**Issue by kumaro** [linvi/tweetinvi#1083]
Looks like the previous version has SearchResultType.Popular. Is this available for Twitter V2 ?

**Comment by linvi** [comment]
Hi there.

It does not seem to be the case at the moment based on Twitter documentation.

* https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-rule
* https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent

It is a shame, but I would suggest to send feedback here : https://twitterdevfeedback.uservoice.com/forums/921790-twitter-developer-labs.
If you do please share the link to your request so that I can upvote it too!

Cheers,
Linvi

**Comment by fightlikeagirl** [comment]
Well, I did this : https://twitterdevfeedback.uservoice.com/forums/921790-twitter-developer-labs/suggestions/42344605-bring-back-search-type-popular-on-recent-search
