### ISSUE TITLE
Possible memory leak with streams

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#109]
https://tweetinvi.codeplex.com/workitem/2664?FocusElement=CommentTextBox#

Hi, 

I understand this could probably be / probably is caused by my misunderstanding. But I having out of memory exceptions when running multiple streams over multiple accounts.

In one instance, it was just 5 "followers streams" (watching for new followers to my accounts). It would take a day or so and the out of memory exception would hit.

Another case is trying to connect to a lot more streams (50+)

Are there any "known" gotchas that might explain this? Something I am not releasing handling correctly?

Cheers

**Comment by JoshKeegan** [comment]
This might be related, or it might be a separate issue in my code, I've never looked into it as it isn't a priority.
I have an application running > 100 user streams and it can run without issue for weeks. Memory usage isn't particularly high (not enough for me to be concerned), but then it (I assume) memory usage increases sharply as I'll come back in the morning to find it having died with an OutOfMemoryException.

It's designed to try and start a replacement for a failed stream several seconds after it disconnecting, so this could easily be being caused by a resource not being cleaned up when a stream disconnects.

Like I said, I haven't looked into this, but seems likely it's the same issue so let me know if you need any info or help tracking the leak down.

**Comment by linvi** [comment]
I have performed some memory leak testing and I do not think these memory leaks come from Tweetinvi. At least I have not found any memory leak in Tweetinvi version 0.9.11.0.

In order to test I created a `FilteredStream` with various keywords and run it for a straight 6 hours.
The memory has been stable at ~2.73 MB. The lowest being 2.69MB  and highest 2.80MB. And this last value was probably due to a GC cycle that was not forced.

Here is a screenshot of the measures :

![test-memory](https://cloud.githubusercontent.com/assets/6107439/12892156/b3c8ff0a-ce82-11e5-9563-0db926ffca7b.png)

It would be great if you could both send me your registration and deregistration of the Stream and Global events.

If you have access to [RedGate ANTS Memory Profiler](https://www.red-gate.com/products/dotnet-development/ants-memory-profiler/) or [JetBrains Dot Memory](https://www.jetbrains.com/dotmemory/) I would be interested to have some screenshots of the memory evolution.

Specially regarding the type of orphaned objects that have not been destroyed.
If you have RedGate ANTS Memory Profiler it would useful to let me know which method is causing your memory leak.

**Comment by JoshKeegan** [comment]
Hi Linvi,
This hasn't happened for me since 20th Jan, when I won't have been on Tweetinvi version 0.9.11.0.
So before spending any time on this I'll wait and see if it happens again in production and if so try and come up with a way to reproduce it on my machine.

As I said before I haven't looked into it at all yet, so the problem could be elsewhere.
Cheers,
Josh

**Comment by linvi** [comment]
Ok, please do check this out. I will close this issue for now.
Ping me back if you encounter the problem again.

**Comment by JoshKeegan** [comment]
Happenned again in the early hours of this morning. Looking at the logs, not a whole lot was happenning before it crashed (no errors or streams disconnected for days before) so nothing to go on.

We unfortunately don't have a license for a memory profiler, but I thought I'd give the new free memory usage stats in VS 2015 a try :) It's definately better than any other free tool I've used for this, but falls well short of ANTS (haven't tried Dot Memory).
Unfortunately, once it had opened all of the streams it sits rock solid, with no new objects being created and the heap size unchanging:
![streaming listener memory usage](https://cloud.githubusercontent.com/assets/1682204/13316950/7a80f6b4-dbaa-11e5-93d5-9cb2c4939b7f.jpg)
This is no big surprise since in production it can work fine for weeks, but dissapointing because I still haven't been able to pin-point the problem.

Re-reading the original posters description of when he was getting the memory leaks, my problem doesn't actually sound like it's the same. We routinely run over 100 streams with no memory problems and the original post seems to imply that running 50 is impossible for them.
