### ISSUE TITLE
trying to extract video from tweet.Entitities.Media

### ISSUE THREAD

**Issue by misterraj7** [linvi/tweetinvi#119]
I am trying to extract twitter videos from a tweet. 
I am doing the following:

var searchParameter = Search.CreateTweetSearchParameter("dubsmash");

           
                    searchParameter.SearchType = SearchResultType.Popular;
               
               
                searchParameter.Filters = TweetSearchFilters.Videos;
                searchParameter.MaximumNumberOfResults = 50;
              
                searchParameter.TweetSearchType = TweetSearchType.OriginalTweetsOnly;
                var tweetList = Search.SearchTweets(searchParameter);

             
                foreach (var tweet in tweetList)
               {
              string url = tweet.Entities.Media[0].ExpandedURL 
               }

the url value thus returns( for example)
http://twitter.com/ERA_fm/status/691183877411328001/video/1

this is a page actually and not the video file. Has any one extracted the video file that is uploaded in twitter.

sometimes the value of video URL's are set in tweet.Entities.Urls which was easy to take but sometimes the uploaded videos are also found in tweet.Entities.Media[0]. Has any one encountered this problem??

**Comment by linvi** [comment]
This is an issue of the Twitter Search API as explained here : https://twittercommunity.com/t/twitter-video-support-in-rest-and-streaming-api/31258/50?u=tweetinviapi.

I have created a post regarding your problem here : https://twittercommunity.com/t/video-entities-are-empty-in-search-result/60646.

Finally here is how you can get the tweet video url currently.

``` c#
var tweetList = Search.SearchTweets(searchParameter);
var tweetIds = tweetList.Select(x => x.Id);

// Get the Tweets again from twitter
var tweetsWithVideoInfo = Tweet.GetTweets(tweetIds.ToArray());

foreach (var tweet in tweetsWithVideoInfo)
{
    var url = tweet.Entities.Medias[0].VideoDetails.Variants[0].URL;
}
```

**Comment by misterraj7** [comment]
tweet.Entities.Medias[0].VideoDetails - always returns null.

**Comment by linvi** [comment]
Have you used the code I sent?

**Comment by misterraj7** [comment]
Exactly. The videoDetails returns null.

**Comment by linvi** [comment]
Could you share the id of the tweet you are trying to analyse please.

**Comment by misterraj7** [comment]
I understand sometimes the videos will be available in tweet.Entities.Urls and sometimes in tweet.Entities.Medias; When it is in tweet.Entities.Urls it works perfectly but when it is available in tweet.Entities.Medias the tweet.Entities.Medias[0].VideoDetails are always NULL. I am using version 0.9.6.1.

**Comment by linvi** [comment]
First of all, I would usually recommend to upgrade. But please share the tweet id. I will investigate the json.

**Comment by misterraj7** [comment]
694047635326414848
693492020350951429

**Comment by misterraj7** [comment]
more id's
694047360154927105
691183691897270272

**Comment by linvi** [comment]
Hello there, I am sorry but only the first id works for me and the result I receive contains the video_details.

Could you make sure of the ids please? Thanks

**Comment by misterraj7** [comment]
It Perfectly works. Thank you.

whats the difference between ?
var tweetList = Search.SearchTweets(searchParameter); 
**and**
var tweetList = Search.SearchTweets(searchParameter);
var tweetIds = tweetList.Select(x => x.Id);

// Get the Tweets again from twitter
var tweetsWithVideoInfo = Tweet.GetTweets(tweetIds.ToArray());

**Comment by linvi** [comment]
The problem is the fact that `Search.SearchTweets(searchParameter);` does not return Video Details as explained on the twitter forums.

But `Tweet.GetTweets(tweetIds.ToArray());` (`https://api.twitter.com/1.1/statuses/lookup.json`) does return the Video Details. So what this code is actually doing is retrieving the ids of the tweet from the search query. And then retrieve all the tweets again from  `Tweet.GetTweets`.

If you read the [twitter thread](https://twittercommunity.com/t/video-entities-are-empty-in-search-result/60646/3), AndyPiper also suggested the same solution for this problem.
