### ISSUE TITLE
How to delete all timeline tweets

### ISSUE THREAD

**Issue by diogo98s** [linvi/tweetinvi#142]
Hello!
I'm new here in coding, although I think I manage to understand what I've seen (until now!)

As the title says, is is possible to delete all tweets from the timeline? And if it is possible, could you explain as if I were a beginner? Because that's what I am.

Thanks! :D

**Comment by linvi** [comment]
Hello,

What I would currently suggest is that you retrieve all the tweets you want to destroy from your timeline with the following code:

``` c#
Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");
RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;

var authenticatedUser = User.GetAuthenticatedUser();
var tweetsToDestroy = Timeline.GetUserTimeline(authenticatedUser, 3200).ToArray();

// Twitter provide neither bulk destroy nor rate limits for the destroy endpoint so we will have to be messy

for (var i = 0; i < tweets.Length; ++i)
{
    var tweet = tweets[i];
    var destroyOperationSucceeded = tweet.Destroy();

    if (!destroyOperationSucceeded)
    {
        // Ensure that the tweet still exist
        var verification = Tweet.GetTweet(tweet.Id);
        if (verification != null)
        {
            // Waiting for 30 seconds for the credentials to be available.
            Task.Delay(30000);

            // Let's try again to delete the tweet
            --i;
        }
    }
}
```

Please note that this code can take a lot of time because of the RateLimits.
The `RateLimitTrackerMode.TrackAndAwait` is handling them for you.

Also please note that you cannot access more than 3200 tweets with the Twitter API.
If you want to destroy the remaining you can call the same operation again up to the point where `Timeline.GetUserTimeline(authenticatedUser, 3200)` returns 0 tweet.

**Comment by linvi** [comment]
Please be aware that for bulk delete you must ensure that the user knows about it.

> Automated deleting
Deleting Tweets in a bulk or automated manner is permitted only with prior express user consent. Your application must clearly state that in the event Tweets are deleted, they will not be recoverable.

Source : https://support.twitter.com/articles/76915#deleting

**Comment by diogo98s** [comment]
Yes, that was it. Thank you!
