### ISSUE TITLE
NullReference Exception : To Verify

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#160]
From Gitter : 

Hi! Just updated to tweetinviAPI.0.9.11.1 using NuGet package manager. The ',' char is now well handled when publishing tweets, thanks a lot! Still experiencing the same NullReferenceException when one of my OAuth keys is misspelled, though.

**Comment by XavierWielemans** [comment]
`NullReferenceException` is thrown by `Tweetinvi.Core.Exceptions.SingleAggregateExceptionThrower.ExecuteActionAndThrowJustOneExceptionIfExist(Action action)`.

**Comment by linvi** [comment]
I could not reproduce the problem but I made the code Null safe.

Let me know if this solve your problem when I release Tweetinvi version 0.9.11.2.

**Comment by XavierWielemans** [comment]
Hi Linvi,
Just updated NuGet package to 0.9.11.2 (verified that the update had
succeeded). No change, sorry! Still the same null ref thrown from inside
`ExecuteActionAndThrowJustOneExceptionIfExist`...
Do you want me to try and integrate the source code of tweetinvi instead of
the nuget package, so that I can use VS debugger and get more details about
how/why/when the exception is thrown?

On Sun, Mar 20, 2016 at 1:32 AM, linvi <notifications@github.com> wrote:

> I could not reproduce the problem but I made the code Null safe.
>
> Let me know if this solve your problem when I release Tweetinvi version
> 0.9.11.2.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linvi/tweetinvi/issues/160#issuecomment-198814751>
>



-- 

tiny*big*story sprl

Avenue de la Paix 44
B-1420 Braine-l'Alleud
Belgique
+32 472 98 56 97
xavier@tinybigstory.be
skype: xavier.wielemans

TVA BE 0501.800.004
ING 363-1136573-64

**Comment by linvi** [comment]
That would be idea if you could do that. 
Sorry if it was not fixed by the change I did.

**Comment by XavierWielemans** [comment]
No problem. Glad to contribute!
Do I simply get the code from github and add it to my VS project? Or is it
more complex than that? I'm no big expert of VS, sorry...


On Thu, Mar 24, 2016 at 2:14 PM, linvi <notifications@github.com> wrote:

> That would be idea if you could do that.
> Sorry if it was not fixed by the change I did.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linvi/tweetinvi/issues/160#issuecomment-200825569>
>



-- 

tiny*big*story sprl

Avenue de la Paix 44
B-1420 Braine-l'Alleud
Belgique
+32 472 98 56 97
xavier@tinybigstory.be
skype: xavier.wielemans

TVA BE 0501.800.004
ING 363-1136573-64

**Comment by linvi** [comment]
No there is nothing special to do.
You can simply get the master branch from Github.

Then I would suggest the following steps :

1. Open Tweetinvi.sln in visual studio
2. Right Click on the solution `Solution 'Tweetinvi' (13 projects)` > `Add` > `Existing Project`
3. Select your project `.csproj`
4. In your solution change your references to use the Tweetinvi projects instead of the DLL.

Add the following:
* Tweetinvi
* Tweetinvi.Controllers
* Tweetinvi.Core
* Tweetinvi.Credentials
* Tweetinvi.Factories
* Tweetinvi.Logic
* Tweetinvi.Security
* Tweetinvi.Streams
* Tweetinvi.WebLogic

Thanks

**Comment by XavierWielemans** [comment]
Hi Linvi!
Thanks for your help, I followed your procedure and could rebuild my
project using the source files I got from GitHub. I wouldn't have managed
it without your help I think, and I learned a number of things along the
way... :)
So... The null ref actually happens in
`Tweetinvi.Factories/User/UserFactory.cs`, at line 56 :
`authenticatedUser.SetCredentials(credentials);`. authenticatedUser is null
so calling SetCredentials throws the exception.

Call stack trace:

   at
Tweetinvi.Factories.User.UserFactory.GetAuthenticatedUser(ITwitterCredentials
credentials, IGetAuthenticatedUserParameters parameters) in d:\Backup
Tiny\Inytium\Tour
cybernétique\VisualStudio\InteractionManager\tweetinvi-master\Tweetinvi.Factories\User\UserFactory.cs:line
56
   at Tweetinvi.Streams.UserStream.<StartStreamAsync>b__18_0() in d:\Backup
Tiny\Inytium\Tour
cybernétique\VisualStudio\InteractionManager\tweetinvi-master\Tweetinvi.Streams\UserStream.cs:line
120
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

I put a breakpoint at the beginning of that method (Ln 42 in same file) and
stepped through it with the debugger. I noticed that both method arguments,
credentials and parameters, were null at that point. Credentials is given a
non-null value by _credentialsAccessor.CurrentThreadCredentials, but
userDTO remains null even
after _userFactoryQueryExecutor.GetAuthenticatedUser(parameters) has been
executed. Maybe that's why the return value
of GenerateAuthenticatedUserFromDTO(userDTO) is also null?

Tell me if I can do other tests...

Cheers,

Xavier

PS: I'm using VS Community 2015 on Win 7 Pro 64bit.

On Thu, Mar 24, 2016 at 4:55 PM, linvi <notifications@github.com> wrote:

> No there is nothing special to do.
> You can simply get the master branch from Github.
>
> Then I would suggest the following steps :
>
>    1. Open Tweetinvi.sln in visual studio
>    2. Right Click on the solution Solution 'Tweetinvi' (13 projects) > Add
>    > Existing Project
>    3. Select your project .csproj
>    4. In your solution change your references to use the Tweetinvi
>    projects instead of the DLL.
>
> Add the following:
>
>    - Tweetinvi
>    - Tweetinvi.Controllers
>    - Tweetinvi.Core
>    - Tweetinvi.Credentials
>    - Tweetinvi.Factories
>    - Tweetinvi.Logic
>    - Tweetinvi.Security
>    - Tweetinvi.Streams
>    - Tweetinvi.WebLogic
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linvi/tweetinvi/issues/160#issuecomment-200899361>
>



-- 

tiny*big*story sprl

Avenue de la Paix 44
B-1420 Braine-l'Alleud
Belgique
+32 472 98 56 97
xavier@tinybigstory.be
skype: xavier.wielemans

TVA BE 0501.800.004
ING 363-1136573-64

**Comment by XavierWielemans** [comment]
PS: the former test was with a misspelled oauth key.
I did the same test with the 4 keys spelled correctly. This time calling _
userFactoryQueryExecutor.GetAuthenticatedUser(parameters) returned a non
null userDTO, and GenerateAuthenticatedUserFromDTO(userDTO) then returns a
non null authenticated user => no more null ref exception when calling
SetCredentials on it.

On Fri, Mar 25, 2016 at 2:28 PM, Xavier Wielemans <xavier@tinybigstory.be>
wrote:

> Hi Linvi!
> Thanks for your help, I followed your procedure and could rebuild my
> project using the source files I got from GitHub. I wouldn't have managed
> it without your help I think, and I learned a number of things along the
> way... :)
> So... The null ref actually happens in
> `Tweetinvi.Factories/User/UserFactory.cs`, at line 56 :
> `authenticatedUser.SetCredentials(credentials);`. authenticatedUser is null
> so calling SetCredentials throws the exception.
>
> Call stack trace:
>
>    at
> Tweetinvi.Factories.User.UserFactory.GetAuthenticatedUser(ITwitterCredentials
> credentials, IGetAuthenticatedUserParameters parameters) in d:\Backup
> Tiny\Inytium\Tour
> cybernétique\VisualStudio\InteractionManager\tweetinvi-master\Tweetinvi.Factories\User\UserFactory.cs:line
> 56
>    at Tweetinvi.Streams.UserStream.<StartStreamAsync>b__18_0() in
> d:\Backup Tiny\Inytium\Tour
> cybernétique\VisualStudio\InteractionManager\tweetinvi-master\Tweetinvi.Streams\UserStream.cs:line
> 120
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
>
> I put a breakpoint at the beginning of that method (Ln 42 in same file)
> and stepped through it with the debugger. I noticed that both method
> arguments, credentials and parameters, were null at that point. Credentials
> is given a non-null value by _credentialsAccessor.CurrentThreadCredentials,
> but userDTO remains null even
> after _userFactoryQueryExecutor.GetAuthenticatedUser(parameters) has been
> executed. Maybe that's why the return value
> of GenerateAuthenticatedUserFromDTO(userDTO) is also null?
>
> Tell me if I can do other tests...
>
> Cheers,
>
> Xavier
>
> PS: I'm using VS Community 2015 on Win 7 Pro 64bit.
>
> On Thu, Mar 24, 2016 at 4:55 PM, linvi <notifications@github.com> wrote:
>
>> No there is nothing special to do.
>> You can simply get the master branch from Github.
>>
>> Then I would suggest the following steps :
>>
>>    1. Open Tweetinvi.sln in visual studio
>>    2. Right Click on the solution Solution 'Tweetinvi' (13 projects) >
>>    Add > Existing Project
>>    3. Select your project .csproj
>>    4. In your solution change your references to use the Tweetinvi
>>    projects instead of the DLL.
>>
>> Add the following:
>>
>>    - Tweetinvi
>>    - Tweetinvi.Controllers
>>    - Tweetinvi.Core
>>    - Tweetinvi.Credentials
>>    - Tweetinvi.Factories
>>    - Tweetinvi.Logic
>>    - Tweetinvi.Security
>>    - Tweetinvi.Streams
>>    - Tweetinvi.WebLogic
>>
>> Thanks
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/linvi/tweetinvi/issues/160#issuecomment-200899361>
>>
>
>
>
> --
>
> tiny*big*story sprl
>
> Avenue de la Paix 44
> B-1420 Braine-l'Alleud
> Belgique
> +32 472 98 56 97
> xavier@tinybigstory.be
> skype: xavier.wielemans
>
> TVA BE 0501.800.004
> ING 363-1136573-64
>



-- 

tiny*big*story sprl

Avenue de la Paix 44
B-1420 Braine-l'Alleud
Belgique
+32 472 98 56 97
xavier@tinybigstory.be
skype: xavier.wielemans

TVA BE 0501.800.004
ING 363-1136573-64

**Comment by linvi** [comment]
Thanks, it now solved and will be released as part of version 0.9.12.0.

Please not that if you encountered this issue it probably meant that the credentials were not correctly set when calling the `StartStream`.

Please note that `Stream` credentials are set up from the `ThreadCredentials` of the `Thread` in which the `Stream` is constructed (via `Stream.CreateUserStream()`).

**Comment by XavierWielemans** [comment]
Thanks a lot Linvi!
I will test that when the 0.9.12.0 is released.
Here is my code:

`var cred = Auth.SetUserCredentials(consumerKey, consumerKeySecret,
accessToken, accessTokenSecret);
Auth.ApplicationCredentials = new TwitterCredentials(consumerKey,
consumerKeySecret, accessToken, accessTokenSecret);
Console.WriteLine("Creating sample stream...");
var stream = Tweetinvi.Stream.CreateUserStream();
Console.WriteLine("Registering event callback...");
stream.TweetCreatedByAnyoneButMe += (sender, twargs) => {
    // ...
};
stream.FollowedByUser += (sender, twargs) => {
    // ...
};

Console.WriteLine("Starting stream...");

stream.StartStream();`

Am I doing sth wrong with the creds? The double use of
`Auth.SetUserCredentials` and `Auth.ApplicationCredentials` seems a little
weird. I copy-pasted if from your wiki but maybe I understood wrong?


On Fri, Mar 25, 2016 at 3:47 PM, linvi <notifications@github.com> wrote:

> Thanks, it now solved and will be released as part of version 0.9.12.0.
>
> Please not that if you encountered this issue it probably meant that the
> credentials were not correctly set when calling the StartStream.
>
> Please note that Stream credentials are set up from the ThreadCredentials
> of the Thread in which the Stream is constructed (via
> Stream.CreateUserStream()).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/linvi/tweetinvi/issues/160#issuecomment-201319677>
>



-- 

tiny*big*story sprl

Avenue de la Paix 44
B-1420 Braine-l'Alleud
Belgique
+32 472 98 56 97
xavier@tinybigstory.be
skype: xavier.wielemans

TVA BE 0501.800.004
ING 363-1136573-64
