### ISSUE TITLE
Consider moving the CredentialsCreator into Auth

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#163]
To consider.

**Comment by linvi** [comment]
@JoshKeegan what do you think about this?

Maybe a simple rename?

Thanks for your help ;)

**Comment by JoshKeegan** [comment]
I'd go with keeping it separate from Auth. 

From a quick skim read of both files they appear to have separate responsibilities, with CredentialsCreator interacting with Twitter and Auth working on local representations of Credentials, so I quite like them as is because of that.

As for renaming, I can't really think of an amazing name. Perhaps AuthFlow would be descriptive of what it does and be more consistent with the Auth class name?
