### ISSUE TITLE
web request timed out.

### ISSUE THREAD

**Issue by rdahan156** [linvi/tweetinvi#182]
Exception.Message: https://stream.twitter.com/1.1/statuses/filter.json?follow=363640677%2C176566242%2C181561712%2C84279963&stall_warnings=true web request timed out.
Exception.StackTrace:    at Tweetinvi.Streams.StreamTask.GetJsonResponseFromReader(StreamReader reader, ITwitterQuery twitterQuery)
   at Tweetinvi.Streams.StreamTask.Start()
Exception DateTime: 30/03/2016 21:53:38

**Comment by linvi** [comment]
Thank you again for reporting this :)

Are you still working with version 0.9.11.2?
If yes, have tried to change the `TweetinviConfig.WebRequestTimeout`?
Is the error happening right away or is it happening after you've been able to retrieve some tweets?

**Comment by rdahan156** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15278944/14174086/d0b07af8-f74a-11e5-8893-0c8880276abe.png)

**Comment by linvi** [comment]
Sorry I thought I sent a reply to this post.
Apparently we can see that the stream attempts to start multiple times.
This could be caused by Twitter taking too much time to reply or the connection being too slow.

I would either suggest to increase the timeout or leave it as is.
The reason being that we can see that the stream is starting at some point so the problem only comes from the fact that Twitter is too slow to return an Http Response.
