### ISSUE TITLE
Get Retweeters ID

### ISSUE THREAD

**Issue by lcumra** [linvi/tweetinvi#208]
I have a list of tweets for whom I need to retrieve all the retweeters ID,

I am currently using
                            var reet = Tweetinvi.Tweet.GetRetweetersIds(twit).ToList();

but this gives an empty list as a result for no matter which tweetId
I have seen you are currently working on related issues, so I wonder if you could help me understanding how to retrieve the list of retweeters IDs and whether you have a way to cursor the query;

Thank you for your help

**Comment by linvi** [comment]
We will have a look and make sure this is working before helping you.

**Comment by haseeb1431** [comment]
I just executed following query and it returned me list of ids.

var ids = Tweet.GetRetweetersIds(210462857140252672);

Can you share complete code or some tweet ids you're trying?

**Comment by lcumra** [comment]
i have just checked with the tweet id you provided and it works, apparently a lot of the tweets I had in my dataset belong to users who changed their privacy settings and I had enough bad luck to select those.

Anyway, I am having a hard time finding how to make a cursored query to catch > 100 retweeters. If you could help me with that, it'd be highly appreciated. Thank you again!

**Comment by linvi** [comment]
Tweetinvi has a lack regarding cursor queries. At the current time you only have 2 options.
Either set the maximum number of items you want to receive or do the queries manually via the `TwitterAccessor`.

You can find an example of the `TwitterAccessor` in order to get all the followers [here](https://github.com/linvi/tweetinvi/wiki/Get-All-Followers-Code). You can adapt it very easily by changing the parameters and the query.

Please note that we have plans to improve cursor queries in the future https://github.com/linvi/tweetinvi/issues/187.

**Comment by linvi** [comment]
Have you been able to do what you wanted? Can I close this issue?
