### ISSUE TITLE
multiple streams?

### ISSUE THREAD

**Issue by jcmag** [linvi/tweetinvi#216]
Hi,
Is it possible to start multiple streams at the same time?
I did a quick test, but I only receive messages from one stream...

**Comment by linvi** [comment]
It depends of the type of stream that you want to use.

* `UserStreams` are not limited. You can run concurrently any different user stream.
* `FilteredStreams` and `SampleStreams` are in theory limited to one, but you can usually run 2 concurrently with the same credentials. If you have a second set of credentials you should be able to run more than 2. But be careful because Twitter will check you IP and "ban" your account if you do not respect their rule. Therefore I usually advise to have FilteredStreams running on multiple IPs if you want to run them concurrently.

Hope this helps.

**Comment by jcmag** [comment]
ok, as I have to monitor dozens of accounts, I'll stay with the REST api.
Thanks!

**Comment by linvi** [comment]
If you want to monitor accounts for which you have access to credentials, you can use the `UserStream`.

The `FilteredStream` also has a `.AddFollow` that will let you get tweets for up to 5000 users.

**Comment by jcmag** [comment]
ah ok, I'll try with AddFollow, thanks again ;)

**Comment by jcmag** [comment]
FilteredStream with addFollow works great.
I'm checking the source of tweets, with a userById dictionary, as you explained [here](https://github.com/linvi/tweetinvi/issues/113). But it seems I'm also getting replies; is there a way to only get tweets that are displayed on user's walls?

**Comment by linvi** [comment]
I would suggest that you take a look into [MatchOn](https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.Core/Interfaces/Streaminvi/MatchOn.cs).

``` c#
var fs = Stream.CreateFilteredStream();
fs.MatchOn = MatchOn.Follower;
```

Also note that you can get the list of all the user ids who have been matched in the tweet like this:

``` c#
fs.MatchingTweetReceived += (sender, args) =>
{
    var userIdsTrackedMatchedInTheTweet = args.MatchingFollowers;
};
```

Finally, if you like tweetinvi don't forget to star it and follow it so that you can be informed of the latest updated :)
