### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by EMartirosyan** [linvi/tweetinvi#218]
I receive rate limit exceed exception. 
Code: 429
Error documentation description: Too Many Requests - Returned in API v1.1 when a request cannot be served due to the application's rate limit having been exhausted for the resource.

What is strange is that I set:
RateLimit.RateLimitTrackerMode = Tweetinvi.Core.RateLimitTrackerMode.TrackAndAwait;

So, I expect it to track the limits. What can I do wrong ?
I have a simple application with only 1 main thread which make requests to Twitter synchronously.

**Comment by linvi** [comment]
Hello,

The problem is that Twitter does not provide all the information required for all the endpoints in their RateLimit endpoint. All the endpoints for which Twitter list the information will be handled. The other endpoints won't be handled.

This is the reason why we currently have a new feature that will be implemented in version 0.9.13.0.

https://github.com/linvi/tweetinvi/issues/191

Before this you will have to handle the exception on your own.

**Comment by linvi** [comment]
Sorry about that, this is temporary. I will send a message here as soon as the feature has been implemented.

**Comment by EMartirosyan** [comment]
Ok, thank you for your help and rapid answer.

**Comment by linvi** [comment]
The new solution for RateLimit handling has now been implemented.
To make sure that it will work for you, could you please let me know which endpoint you were caliing?
Which code was throwing an exception.

Thanks
