### ISSUE TITLE
How to get all tweets in the date range?

### ISSUE THREAD

**Issue by stenly311** [linvi/tweetinvi#247]
Hey, 

I am having a trouble to come up with the solution which could give me all tweets matching searching criteria and not to restrict response collection set on MaximumNumberOfResults value. 

_Speaking in example:_ 
I have since and until date time range set on a day, location and radius and now I want to get all tweets regardless on how many of them are available. The best solution saves the rank of requests needed to trigger from client side. 

Thanks in advance

**Comment by JoshKeegan** [comment]
I think you could set MaximumNumberOfResults to `int.MaxValue`, which is a little hacky but should work unless you expect to have in excess of ~2bn results. 
I don't know how well Tweetinvi will handle the rate limits for the Search API endpoint here though (so if it took 1000 API requests to get all of the results you're interested in, would Tweetinvi wait the correct amount of time between requests or exceed the rate limits and error). It might be fine, but I've never tried it.

Alternatively, you could set the maximum to 100 (or just not touch it) and handle the paging yourself, making lots of requests for 100 results each in a loop. You'd just need to specify Since ID for the next call based on the results of the last API call. The advantages of this are that it isn't hacky & lets you handle the rate limits yourself, so you could look to do things like switching the credentials you're using between requests so you can make more requests per window, but it's a bit more complex to implement.

**Comment by stenly311** [comment]
Hi Josh, 
this is how I did originally use it. Int.MaxValue works fine and i was wondering if you guys figured it how to get over 100 tweets/request in order to save few requests from dedicated rate limit.

I see a that library is looping until number of results is matching (regardless how many requests has been used, I guess she goes efficiently per entire possible batch of tweets/request).

Only 2 cents for nice to have feature would be that if no Max is specified than gives me everything. 

Thanks.

**Comment by haseeb1431** [comment]
@stenly311 This is something that we cannot do anything since it is a limitation from the twittler API. We can have maximum 100 hundred tweets per page as mentioned in API documentation.
https://dev.twitter.com/rest/reference/get/search/tweets

**Comment by linvi** [comment]
@stenly311 

> Only 2 cents for nice to have feature would be that if no Max is specified than gives me everything.

I understand your point but this has been done intentionally. The reason is that I don't want users to say `Search.SearchTweets` and have Tweetinvi consumer the entire set of search RateLimits.

I think it is more reasonable for the user to ask for such behaviour.
