### ISSUE TITLE
Give the ability to developers to set how the current DateTime is retrieved.

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#271]
If an end user of a phone, has an incorrect DateTime we still want to be able to use Tweetinvi.

**Comment by JoshKeegan** [comment]
I see the problem this will solve, but it can only happen because the request is being signed from a device you don't control (e.g. end-user phone). By doing so, you must have given your application consumer key & secret to this untrusted device. 

I appreciate many developers won't care about this, so I do think this should be included in Tweetinvi, but I think it's important to make sure it comes with a big warning about running requests directly from untrusted devices. Anyone worried about the security implications should send the request to their own server and then make the request to Twitter from there (which would bypass any device time issues as the request is signed by the server), or if one day Tweetinvi supported external request signing (see discussion in #68) that also should solve this problem without requiring the untrusted device to have your app credentials.

**Comment by linvi** [comment]
Yes I think there are some security issues but many developers won't care about it. They just want the app to work.

I have planned to work on signed requests for release 1.2 :)
My only concern it the timing. Because the requests are time sensitive, it means that the time it is transported to the client, the request might no longer be valid. But obviously I cannot control the network!

BTW @JoshKeegan could you go on gitter so that we start private chat?
