### ISSUE TITLE
Create a new LanguageFilter enum

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#316]
Streams cannot be filtered with all the existing Languages.
Therefore we want to create a class that will provide only the Languages that can actually be used to Filter a stream.

We can find this list in the language filter for advanced search on twitter.com : https://twitter.com/search-advanced

@JoshKeegan This might be of interest for you

**Comment by JoshKeegan** [comment]
Interesting, I hadn't realised streams couldn't be filtered by arbitrary language codes.

All our searches (currently) get run against the REST API due to its extra params so I probably wouldn't make use of this.
It's worth noting that this doesn't appear to be the case for the REST API. I tested this to make sure I wasn't going mad by searching for tweets of language Kikuyu (code "ki") and got a result of Tweet ID 764505876409573376.

So if this is streaming API specific it might be worth calling it StreamingLanguageFilter or something to that effect :)

**Comment by linvi** [comment]
https://dev.twitter.com/streaming/overview/request-parameters#language

> Setting this parameter to a comma-separated list of BCP 47 language identifiers corresponding to any of the languages listed on Twitter’s advanced search page will only return Tweets that have been detected as being written in the specified languages. For example, connecting with language=en will only stream Tweets detected to be in the English language.

**Comment by JoshKeegan** [comment]
Hi Linvi, 
looks like you've changed the REST search as well as the streaming one. What I was trying to say in my previous comment was that this limitation does not apply to the REST API, so that should still use the `Language` enum, not a new `LanguageFilter` with reduced codes.

If you look at the REST API docs (https://dev.twitter.com/rest/reference/get/search/tweets) it doesn't mention only working on a limited set of codes, and this appears to be the case when actually using the codes in searches.

e.g. searching using code "ki" returns results, but isn't in the new `LanguageFilter` enum.

**Comment by JoshKeegan** [comment]
Can be closed after discussion in gitter.
Looks like the REST API treats searches for unsupported languages as being for "lang {x}", e.g. "lang ki".
