### ISSUE TITLE
Destroyed messages are still picked as undestroyed.

### ISSUE THREAD

**Issue by SudeshMascarenhas** [linvi/tweetinvi#358]
When a 'direct message' was deleted by the user in twitter, the 'isMessageDestroyed'  value provided by api is not set as false.  As a result the deleted conversations are picked by the service. Is there any other way to identify the deleted messages? 

> Question

**Comment by linvi** [comment]
If you want to know whether a message has been destroyed you will have to try and get the tweet again or use a stream that will let you know when a tweet is actually being destroyed.

``` c#
// Try to get Tweet
bool hasTweetBeenDestroyed = Tweet.GetTweet(42) == null;

// Stream (works with all of them)
var fs = Stream.CreateFilteredStream();

fs.TweetDeleted += (sender, args) =>
{
    // Tweet has been deleted
};
```

**Comment by SudeshMascarenhas** [comment]
we are actually loading tweet after it has been destroyed from twitter, still the deleted tweets have the 'isMessageDestroyed' property set as true

**Comment by linvi** [comment]
Ok, I will look into it.

**Comment by SudeshMascarenhas** [comment]
any update??

**Comment by linvi** [comment]
Not yet sorry. I was on holiday but I will get back to you during the week.

Sorry for the delay.

**Comment by linvi** [comment]
So I took a look, but I cannot reproduce your issue. Here is the steps I am following to attempt to reproduce your bug:

1. Create a message and store the id
2. Delete the previous message
3. Get the message from its id.

At stage 3, the message received is null which means that the message does not exist.
Could you please be more precise as to what you are attempting to do?

Thanks

**Comment by SudeshMascarenhas** [comment]
I'm not loading any messages as you did
I'm using the below method of the dll to load all the direct messages
**public static IEnumerable<IMessage> GetLatestMessagesReceived(IMessagesReceivedParameters messagesReceivedParameters);**
the loaded messages include even the destroyed messages

**Comment by SudeshMascarenhas** [comment]
And  also the destroyed messages have the isDestroyed property set to false

**Comment by linvi** [comment]
Thanks, I will do further investigation on this issue.
Sorry for the delays but the end of years are usually very busy for me.

**Comment by SudeshMascarenhas** [comment]
Waiting for your reply....

**Comment by linvi** [comment]
Hello there. I am very sorry about the delays that you had to experience. I am working on 3 projects at the same time and I do not have enough time to track all the issues.

Regarding your issue. Could you please provide some code that allow you to reproduce this bug every time. I have tried again today without any success.

**Comment by SudeshMascarenhas** [comment]
[TwitterSample.txt](https://github.com/linvi/tweetinvi/files/609112/TwitterSample.txt)

Hi,

I could not attach the zip file. I have attached the text file containing the sample code. If you need more information please let me know. This bug needs to be resolved as soon as possible.

Thanks,
Sudesh

**Comment by SudeshMascarenhas** [comment]
I have sent a mail with zip file containing the sample code attached

**Comment by SudeshMascarenhas** [comment]
Can you please look into the issue as soon as possible?

**Comment by linvi** [comment]
Hello, once again sorry for this very long delay. As mentioned it is usually very busy for me during the end of the year and I unfortunately could not focus on Tweetinvi.

Regarding your problem I had a better look, and I think I have found what your problem is.

**In Twitter, a message can be destroyed on the 2 side of the conversation** (`source` and `recipient`).
When you delete a message, you only delete the message from the authenticated account.

If you delete the message from `source` this result in the following : 

* `source` will no longer have the message in its `MessagesSent` 
* `source` will not be able to access the message via its id.
* `recipient` will have access to the message in its `MessagesReceived`
* `recipient` will have access to the message via its id.

Now regarding the `IsMessageDestroyed` property. 

`IsMessageDestroyed` is a calculated property by Tweetinvi and not a value returned by Twitter. 
Twitter cannot return any message that has been destroyed on the account that request it. Therefore this value is always false when a message is received from the Twitter API.

`IsMessageDestroyed` is a helper property that will automatically update when invoking `message.Destroy()` and if the operation is successful this property is changed into `true`.

Let me know if this helped in any way.
