### ISSUE TITLE
Retreiving last hour tweets

### ISSUE THREAD

**Issue by Josh8509** [linvi/tweetinvi#360]
Hello!!! 
Im trying to retreive last hour tweets with the TweetSearchParameters method, my question is if the Since and Until options supports time, this is, when i place the Since option with a datetime object, example DateTime original = DateTime.Now.AddMinutes(-60); it continues giving me results of the whole day.

Thanks for your reply
Josh

**Comment by linvi** [comment]
The Twitter API `since` operator precision is a day (up to 7 days prior to the date you execute your search). 
What I would suggest you do is to combine the `since` and `max_id`. Leave your `since` parameter set but update your `max_id` to iterate over your results up to the DateTime you are interested in.

You can find more about the parameters here : https://dev.twitter.com/rest/reference/get/search/tweets

**Comment by Josh8509** [comment]
Perfect thanks for your reply!!a
