### ISSUE TITLE
Unable to install with NuGet targeting .NET 4.6

### ISSUE THREAD

**Issue by seriema** [linvi/tweetinvi#363]
Running in the package manager of VS 2015:

```
PM> Install-Package TweetinviAPI


Attempting to gather dependency information for package 'TweetinviAPI.1.1.1' with respect to project 'Ascend2016', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 7,18 sec
Attempting to resolve dependencies for package 'TweetinviAPI.1.1.1' with DependencyBehavior 'Lowest'
Install-Package : Unable to resolve dependencies.
At line:1 char:1
+ Install-Package TweetinviAPI
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:09.0536355
```

_Update:_ It doesn't work when I downgrade to .NET 4.5 either. I assumed it would since the NuGet Package Manager listed it among dependencies:
![screenshot 2016-10-11 13 15 28](https://cloud.githubusercontent.com/assets/693684/19268447/d7778144-8fb4-11e6-8d26-7b66b78be916.png)

**Comment by linvi** [comment]
Could you provide all the information concerning your project, is it ASP.NET, Console, UWP, WPF, Winform, Service, .NETCore Library, .NETCore Console or .NETCore ASP.NET.

If possible share a screenshot of the create project in Visual Studio, highlighting the project you want to pick.

**Comment by seriema** [comment]
It's a ASP.NET MVC website project using Episerver CMS, generated with their Visual Studio plugin: https://visualstudiogallery.msdn.microsoft.com/4ad95160-e72f-4355-b53e-0994d2958d3e

**Comment by seriema** [comment]
I tried installing 1.0 as [you requested on gitter](https://gitter.im/linvi/tweetinvi?at=57fcdb60dfe82a365b16c84d). The output's the same:

```
Attempting to gather dependency information for package 'TweetinviAPI.1.0.0' with respect to project 'Ascend2016', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 9,15 sec
Attempting to resolve dependencies for package 'TweetinviAPI.1.0.0' with DependencyBehavior 'Lowest'
Unable to resolve dependencies.
```

**Comment by linvi** [comment]
As asked on gitter, can you please make sure that you have the latest version of Visual Studio and Nuget Package Manager.

**Comment by linvi** [comment]
Bug can be reproduced with EpiServer. I will see what I can do with this.

**Comment by linvi** [comment]
Hello @seriema, there seem to be a problem of compatibility between the version of `Microsoft.Bcl` used by Tweetinvi and the one used by EpiServer.

In addition to this, the project seems to be quite old because it uses old versions of all the libraries as for example `Newtonsoft.Json` (< 9.0.0) whilst Tweetinvi requires a version 9.0.1.

If you still want to use Tweetinvi, you can currently use Tweetinvi version 0.9.14 following this steps :

* Update `Microsoft.Bcl` to version `1.1.1.0`
* Update `Microsoft.Bcl.Async` to version `1.0.168`
* Update `Microsoft.Bcl.Build` to version `1.0.21`
* Update `Microsoft.Net.Http` to version `2.2.29`
* Update `Newtonsoft.Json` to version `8.0.3`

* Install `Tweetinvi` version `0.9.14`

Version > 0.9.14 of Tweetinvi are not currently compatible with `EpiServer` projects.
I will try to find more about the source of the problem and release a hotfix if possible.

**Comment by linvi** [comment]
Please let me know if this helped.

**Comment by seriema** [comment]
@linvi Thank you, that worked! The VS extension might be some version behind on it's Episerver nuget requirements, which are easily updated after the VS project's been generated. I think Newtonsoft 9 support is coming.

I think we can close this issue. It's the nuget output that wasn't very helpful and it's not Tweetinvi's fault.

**Comment by linvi** [comment]
Great, I hope you will like this library :)

**Comment by Nadeem-Saif** [comment]
I tried to install  tweetinvi packages and I got an error as my project is of version 4.6 and some of the dependencies in tweetinivi are not compatible with this version. I have attached a screenshot.

![image](https://user-images.githubusercontent.com/25687717/47282157-cbf2e180-d5fb-11e8-92dc-fccd7a368c1b.png)

**Comment by linvi** [comment]
@Nadeem-Saif please refer to the new bug created for your issue.
