### ISSUE TITLE
Constant 403 exceptions

### ISSUE THREAD

**Issue by gsogol** [linvi/tweetinvi#4]
Hi, I'm constantly getting 403 with "This code is used when requests are being denied due to update limits". On the java forums, folks say you require ssl everywhere and that's what fixed the error. Any thoughts? I'm using 0.9.7.1

**Comment by gsogol** [comment]
I've updated to 0.9.8.2 but still the same. I noticed this only if I hit the api with different content/links like 3-5 in a row, seconds apart. So I get a 403 but the post goes through. Any thoughts?

**Comment by linvi** [comment]
Hi, could you please share your code because obviously RateLimit issues are mostly dependent on what you are doing.

Also please consider reading the [wiki page](https://github.com/linvi/tweetinvi/wiki/Rate-Limits) of rate limits.

I would advise that you investigate your issue with the [RateLimit Tracking mechanism](https://github.com/linvi/tweetinvi/wiki/Rate-Limits#ratelimit-tracking) offered by Tweetinvi.

Please keep me up to date.

**Comment by linvi** [comment]
Any news here?

**Comment by gsogol** [comment]
Twitter was saying rate limit but the real message turned out to be that the text needs to be no more than 117 when uploading with media. You can close.

**Comment by linvi** [comment]
Ok, There various parameters to consider like links, hashtags, mentions and medias.

Tweetinvi offers different solution to calculate the length of a Tweet. 

``` c#
var tweet = Tweet.CreateTweetWithMedia("hello", new byte[20]);
var twitterLength = tweet.Length;
var remaining = tweet.TweetRemainingCharacters();
```

Hope this helps you out.
And enjoy tweetinvi.

**Comment by gsogol** [comment]
Nice thanks
