### ISSUE TITLE
Friendship.GetRelationshipDetailsBetween(user,user2) What does it Output and...

### ISSUE THREAD

**Issue by Unkindjolt** [linvi/tweetinvi#458]
I'm trying to check if at the time of receiving a Tweet to be Retweeted, if the user is following, Is it possible to use 

``` c#
Auth.SetUserCredentials(Key1, Key2, Key3, Key4);
var user = User.GetAuthenticatedUser();
var stream = Tweetinvi.Stream.CreateFilteredStream();
                stream.AddFollow(user);
                stream.MatchingTweetReceived += (sender1, args1) =>
                {  
                  var relationshipDetails = Friendship.GetRelationshipDetailsBetween(user,args1.Tweet.CreatedBy);
                 };
stream.StartStreamMatchingAnyCondition();
'''
And check if .CreatedBy is following the user or am I going in the complete wrong direction here?

Any help is greatly appreciated :) thanks :)

**Comment by Unkindjolt** [comment]
I can't close the Issue, But just a FYI for anyone needing the same thing, I was on the right track, I just didn't know how to Implement it. all I can say without spoon feeding, check var 
```
'insert variable name here'=Friendship.GetRelationshipDetailsBetween(user, args1.Tweet.CreatedBy);

see what these will get you ;)
'insert variable name here'.Following
'insert variable name here'.FollowedBy
```

**Comment by linvi** [comment]
Thank you for the feedback and my apologies for being soooo slow to check your issue.
I hope you are still able to use Tweetinvi as you wanted.

Please note that because `Friendship.GetRelationshipDetailsBetween` is blocking the thread, I would suggest that you open such requests in another thread so that the Stream can continue to run unaffected.

Regards,
Linvi
