### ISSUE TITLE
New Twitter API Change to character allowance.

### ISSUE THREAD

**Issue by Hooper911** [linvi/tweetinvi#487]
Twitter has recently changed there character allowance on replies to now not include the Twitter Username in the 140 character allowance so you are able to send more then the original 140 characters in reply's. If you get a tweet reply in that's more than 140 characters, the message is coming back with a URL inside it for the extra characters.

E.g of message: 
Message added in Twitter: "This is a test message to test the new twitter character count as it has since been extended and now we need to see how the message looks"

Received through TweetInvi API shows as: 
"@TestUserAc This is a test message to test the new twitter character count as it has since been extended and now we… https://t.co/g6rg1esKgV"

*URL no longer valid as it has expired but you get the idea.

**Comment by JoshKeegan** [comment]
Nice!
I hadn't noticed that this was live yet :)
I'll submit a PR for this when I add support to our application (hopefully should get round to it next week).
Cheers,
Josh

**Comment by JoshKeegan** [comment]
When I went to look at adding this in today, it looks like it's already all there! I didn't think all of the changes for the second phase of extended Tweets (moving reply mentions to the prefix) had been done, so that's great! (thanks @Linvi) :)
I haven't used all of the sending part yet, but there's a `AutoPopulateReplyMetadata` property on `IPublishTweetOptionalParameters` that lets you send a reply without including the mentions at the beginning (Twitter adds them in server-side, not counting them towards the body of the tweet).  

Going back to your issue receiving them, this has been supported by Tweetinvi for a while. To get the "extended" Tweet, you can use the `FullText` property of the `ITweet`.  

Before fetching any Tweets over the REST API, run:
```cs
TweetinviConfig.ApplicationSettings.TweetMode = TweetMode.Extended;

// Tweetinvi Application Settings get applied to any new threads spawned.
//  Also apply them to this current thread.
TweetinviConfig.CurrentThreadSettings.InitialiseFrom(TweetinviConfig.ApplicationSettings);
```
which tell the REST API we want extended tweets rather than ones compatible with the old 140 character limit (which puts the URL to the full Tweet on the end, as you've found). This should be the first thing in your application (or at least before any new threads get started).

The only thing I've noticed so far which isn't implemented is `IPublishTweetOptionalParameters.ExcludeReplyUserIds`, which I think is supposed to be equivelant to `exclude_reply_user_ids` on https://dev.twitter.com/overview/api/upcoming-changes-to-tweets, but the Tweetinvi code says "Twitter has not documented this parameter yet!".
This is only important for very long chains of replies though, where you might want to drop some of the auto-mentions to remain within the limit (max 50 mentions in the prefix).

**Comment by Hooper911** [comment]
Thanks Josh, that works great now!

**Comment by linvi** [comment]
Great, thank you @JoshKeegan for looking into this.

I am closing this thread now.

**Comment by JoshKeegan** [comment]
Thanks @linvi 

@Hooper911 see #497 if you need `ExcludeReplyUserIds` (mentioned previously).
Cheers,
Josh
