### ISSUE TITLE
Framework 2.0 for CLR

### ISSUE THREAD

**Issue by joejoe** [linvi/tweetinvi#493]
I would like to write a stored procedure using Tweetinvi. I understand to do this it would need to be a CLR SP, correct?

And to do that, CLR still uses Framework 2.0, at least on MSSQL 2012 and it's  "kind of a thing" if you know what I'm talking about unless it's changed.

But I cannot install Tweetinvi if I'm setup for Framework 2.0 in my CLR app inside of Visual Studio.

Can someone (who specifically has CLR experience, not just winging stuff at the wall) answer me? Thank you for your help in advance.

**Comment by JoshKeegan** [comment]
Hi,
We use SQL Server 2008 R2, which is limited to CLRv2 so I haven't tried this, but I was under the impression that SQL Server 2012+ supported CLRv4.  
Have you tried building something simple targeting .NET4+ and installing it?
Cheers,
Josh

**Comment by joejoe** [comment]
Woops, we are running that too.

So question: Can I do CLR with it needing .NET v2?

**Comment by joejoe** [comment]
OR.... what is the best way to integrate Tweetinvi into MSSQL server so I can use it in TSQL? Thanks.

**Comment by JoshKeegan** [comment]
.NET 3.5 was the last version to target CLRv2, so any code you want to run on SQL Server pre-2012 will need to target .NET 3.5 (or lower).  

So there's 3 options:
1: 
I don't know how much work it would take for Tweetinvi to be compiled against .NET 3.5. To find out, just download the source code & change each project to target .NET 3.5. Then you can try and compile it & count the errors! 

2:
Realistically though, I'd ask yourself why whatever it is you want to do belongs in SQL Server in the first place. You can store data in SQL Server 2008 R2 and process it in a separate application tier (which could be .NET 4.6, or whatever you wanted). There are overheads in getting the data out of SQL Server & then back in again after processing it, but unless you have billions of rows to process this shouldn't be too much of an issue (and even then it's generally better to move processing out of SQL Server due to licencing costs).

3: Buy SQL Server 2012+. If the deadline's tomorrow, you'd better have deep pockets! JK... This would be silly :p If you're buying it anyway in a couple of months (staying nicely ahead of 2008 R2's EOL) then you could just bump up the upgrade schedule?

**Comment by joejoe** [comment]
?? No I want to do something simple: Have the database think for me like any other application. A stored procedure should be able to interact on its own, pulling information. Can I do that in 2008 R2 running now  .NET 4.6?

**Comment by JoshKeegan** [comment]
> .NET 3.5 was the last version to target CLRv2, so any code you want to run on SQL Server pre-2012 will need to target .NET 3.5 (or lower).

Does that answer your question?

**Comment by joejoe** [comment]
I saw that, I was just wondering if Tweetinvi would somehow work on 2008 R2. It's ok though as I got that 2.0 DLL (system.web32 I think?) to compile. I just  tested and it works so I can use another library I have. Thanks.

**Comment by JoshKeegan** [comment]
Yes, it's definatelty possible to run Tweetinvi on SQL Server 2008 R2, although not without changes to the Tweetinvi codebase. It's the first option I mentioned in the earlier post :)

**Comment by joejoe** [comment]
Thanks.

**Comment by linvi** [comment]
Hi just as an addition to this thread, Tweetinvi is targeting .NET 4.0 and above.
I had multiple requests to support more versions but based on the quantity of target that library supports (PCL, .NET Core, W10, Xamarin...) and the important changes that it requires, Tweetinvi will not support .NET 3.5.
