### ISSUE TITLE
need  help.. I can not publish

### ISSUE THREAD

**Issue by tarsomatos** [linvi/tweetinvi#5]
I'm doing something wrong?

        public ActionResult About()
        {
            String UrlContexto = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath;
            // Store the application-only credentials into a variable
            var applicationCredentials = CredentialsCreator.GenerateApplicationCredentials(_consumerKey, _consumerSecret);
            String callBack = UrlContexto + Url.Action("Contact", "Home");
            // Get the URL that the user needs to visit to accept your application
            var url = CredentialsCreator.GetAuthorizationURLForCallback(applicationCredentials, callBack);
            if (url != null)
            {
                return new RedirectResult(url);
            }
            else {
              return View();
            }
        }
        public ActionResult Contact(string oauth_token, string oauth_verifier)
        {
           TwitterCredentials.SetCredentials(oauth_token, oauth_verifier, _consumerKey, _consumerSecret);
           Tweet.PublishTweet("Hello Wolrd Again!");
            return View();
        }

**Comment by linvi** [comment]
Hi, I am not sure you have seen this [part of the documentation](https://github.com/linvi/tweetinvi/wiki/Authentication#web-application-considerations).

It basically says that after the line ` var url = CredentialsCreator.GetAuthorizationURLForCallback(applicationCredentials, callBack);` you need to store the AuthorizationKey and AuthorizationSecret so that you can reuse them in your redirect ActionResult.

So what is wrong with your code is that in your ActionResult you need 2 additional lines:

``` C#
var applicationCredentials = CredentialsCreator.GenerateApplicationCredentials(_consumerKey, _consumerSecret);
applicationCredentials.AuthorizationKey = "WHAT_YOU_STORED";
applicationCredentials.AuthorizationSecret = "WHAT_YOU_STORED";
var newCredentials = CredentialsCreator.GetCredentialsFromCallbackURL(callbackURL, applicationCredentials);
```

I am aware that this is quite a pain. This problem is fixed in Tweetinvi 0.9.9.x which is still in development. But if you get the Source Code on codeplex you will be able to do the following:

``` C#
// About()
var url = CredentialsCreator.GetAuthorizationURL(new ConsumerCredentials("CONSUMER_KEY", "CONSUMER_SECRET"), "https://YOUR_WEBSITE.COM");
// Redirect
```

``` C#
// Contact()
var newCredentials = CredentialsCreator.GetCredentialsFromCallbackURL(entireURLAfterCallback);
var user = Auth.ExecuteOperationWithCredentials(newCredentials, () => { return User.GetLoggedUser(); });
```

**Comment by tarsomatos** [comment]
thanks for helping!!!

then the code would look like this ?
```
String UrlContext = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath;
String callBack = UrlContext + Url.Action("Contact", "Home");

var applicationCredentials = CredentialsCreator.GenerateApplicationCredentials(_consumerKey, _consumerSecret);

var url = CredentialsCreator.GetAuthorizationURLForCallback(applicationCredentials, callBack);

applicationCredentials.AuthorizationKey = _consumerKey;
applicationCredentials.AuthorizationSecret = _consumerSecret;

var newCredentials = CredentialsCreator.GetCredentialsFromCallbackURL(callbackURL, applicationCredentials);

if (url != null)
{
   return new RedirectResult(url);
}
else {
   return View();
}
```

because  declare "newCredentials"  before the redirect?

**Comment by linvi** [comment]
No what you need to do is to store the applicationCredentials in a static object.
After your redirect is complete, use the static variable back in the redirect Action.

The reason as I mentioned is that the applicationCredentials are updated by the `CredentialsCreator.GetAuthorizationURLForCallback` method. At such point they contain the `AuthorizationKey` and `AuthorizationSecret` that will be required when calling `CredentialsCreator.GetCredentialsFromCallbackURL`.

So just store the applicationCredentials in a static object, and reuse it when the redirect action is invoked.

**Comment by linvi** [comment]
So I have checked in some code in Tweetinvi 0.9.9.x. In this branch I have created a new project called Examplinvi.Web. For now there is a simple authentication process that you can reuse.

**Comment by smatthews1999** [comment]
Regarding this statement...

** what you need to do is to store the applicationCredentials in a static object.
After your redirect is complete, use the static variable back in the redirect Action.**

How is this supposed to work with many users all authenticating and posting tweets?  Isn't the static variable going to be overwritten by each call to the web-server?  Am I completely missing something here?

**Comment by linvi** [comment]
If you use the latest version of Tweetinvi this is done for you.
What is happening is that a the redirect url contains a unique identifier allowing to identify the request id. This parameters is called `authorization_id`.

``` c#
public ActionResult TwitterAuth()
{
    var appCreds = new ConsumerCredentials(MyCredentials.CONSUMER_KEY, MyCredentials.CONSUMER_SECRET);
    var redirectURL = "http://" + Request.Url.Authority + "/Home/ValidateTwitterAuth";
    var url = CredentialsCreator.GetAuthorizationURL(appCreds, redirectURL); // The parameter is added here

    return new RedirectResult(url);
}
```

The credentials information required for the authentication process are stored in a static class that is called `CredentialsStore`.

When the callback is received you can use the following code:

``` c#
public ActionResult ValidateTwitterAuth()
{
    var verifierCode = Request.Params.Get("oauth_verifier");
    var authorizationId = Request.Params.Get("authorization_id");

    if (verifierCode != null)
    {
        var userCreds = CredentialsCreator.GetCredentialsFromVerifierCode(verifierCode, authorizationId);
        var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);

        ViewBag.User = user;
    }

    return View();
}
```

Tweetinvi will use the `authorizationId` field and get the credentials information back from the `CredentialsStore`.

This is done behind the scenes and you do not need to worry about it if you don't want to.

If you need more complex logic you can use an other signature of `CredentialsCreator.GetCredentialsFromVerifierCode` which uses `ITwitterCredentials` instead of the `authorizationId`:

``` c#
public ActionResult ValidateTwitterAuth()
{
    var verifierCode = Request.Params.Get("oauth_verifier");
    var authorizationId = Request.Params.Get("authorization_id");
    var creds = MyMethodToGetCreds(authorizationId);

    if (verifierCode != null)
    {
        var userCreds = CredentialsCreator.GetCredentialsFromVerifierCode(verifierCode, creds);
        var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);

        ViewBag.User = user;
    }

    return View();
}
```

**Comment by smatthews1999** [comment]
Thanks for your help.  I have the latest version (0.9.10.2) and I believe I have gotten this far.

My problem is that I am using Web API and cannot for the life of me how to manage the authenticated user, and the acceptance of my app, in the session.  I don't have a database of users and don't want one.  I don't quite understand how the flow is supposed to work.

So far I have...
User attempts to tweet (but user is not authenticated).
Call GetAuthorizationURL() for twitter url.
User goes to Twitter login page and accepts App.
Twitter calls redirect back to my page.
Call GetCredentialsFromVerifierCode() for user creds
Post to Twitter. Yay!

One question I have is ...Now that the user has accepted my app, how to I stop sending them to the Twitter login page?  Apparently this happens by calling  https://api.twitter.com/oauth/authenticate instead of  https://api.twitter.com/oauth/authorize.

My other big question is how do I manage the flow with Web API, which is intended to be stateless, more so than ASP.  There is no session[] or ViewBag.  Again.. I don't have a user storage, so I have no where to put the 4 ids required to authenticate the twitter user.  Do I need to ask the user to authenticate my app every time they use the website?

No offense to your product.... but Twitter API is horrible!  Facebook handles this beautifully.  If the user is logged in to FB on the browser and has authenticated the app then the user is "in like Flynn".. and all on the client.. no server side required..

I looked at some of your examples (Examplinvi.Web) and it seems you are storing the user creds in a static variable MyCredentials.  Is that a one user website?  How could that work?

Any help and guidance would be appreciated.

**Comment by linvi** [comment]
> One question I have is ...Now that the user has accepted my app, how to I stop sending them to the Twitter login page? Apparently this happens by calling https://api.twitter.com/oauth/authenticate instead of https://api.twitter.com/oauth/authorize.

You need to find a way to store the user credentials information (access_token and access_token_secret) somewhere. Either in a database, or as session variables, or as a static dictionary in your WebApi or even in the cookies of the client.

Then you can set up tweetinvi for the current thread/action like this :

``` c#
Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

// All the code after this line will be have the user authenticated.
```

> My other big question is how do I manage the flow with Web API, which is intended to be stateless, more so than ASP. There is no session[] or ViewBag. Again.. I don't have a user storage, so I have no where to put the 4 ids required to authenticate the twitter user. Do I need to ask the user to authenticate my app every time they use the website?

Even though WebApi is stateless you can still use static variables or simply have the client store them and send them for each request either by using the cookies or http headers.

> No offense to your product.... but Twitter API is horrible! Facebook handles this beautifully. If the user is logged in to FB on the browser and has authenticated the app then the user is "in like Flynn".. and all on the client.. no server side required..

This is true only if you use the javascript version of the Facebook api (from my memory). Here you are trying to execute C# code that can live in a Console, Desktop Application, Phone App...

> I looked at some of your examples (Examplinvi.Web) and it seems you are storing the user creds in a static variable MyCredentials. Is that a one user website? How could that work?

`MyCredentials` is intended for the purpose of the example. What you need for all the request is at least your twitter application `CONSUMER_KEY` and `CONSUMER_SECRET`.

These 2 information will allow you to authenticate users.

After the authentication completed, you will receive a new `TwitterCredentials` object containing the 2 information allowing you to authenticate the user (`ACCESS_TOKEN` and `ACCESS_TOKEN_SECRET`).

With these 4 information you will be able to authenticate any user as demonstrated in the first answer and execute any operation from their account.

I hope this is clear.

**Comment by smatthews1999** [comment]
Thanks I will work on it.
