### ISSUE TITLE
How could I cited tweetinvi paper?

### ISSUE THREAD

**Issue by jasonsu123** [linvi/tweetinvi#519]
Dear tweetinvi team,
We started to write a paper, and we use tweetinvi package to extract tweet data.
Our used tweetinvi package version is **"Tweetinvi.0.9.13.0.-.Binaries"**, we are not sure that is the lastest version. 
If you have new version of tweetinvi package, please tell us.
How could I cited your tweetinvi paper if you have?
Thank you
         Best regards;

**Comment by linvi** [comment]
Hello,

The latest version of Tweetinvi is 1.3 and a lot has changed since `0.9.13`.
Quite importantly it includes a "new" feature of Twitter called Extended Tweets.

> How could I cited your tweetinvi paper if you have?

I am not sure what you mean by this.

Regards,
Linvi

**Comment by jasonsu123** [comment]
Thank you, I got it.

How could I get the lastest Tweetinvi  package: "A compressed file that contain Tweetinvi  dills"

How could I cited your tweetinvi paper if you have?

That means that is there any journal paper that related to  Tweetinvi. We start to submit our research paper, and we want to cite the paper of  Tweetinvi.

Thank you
     Best regards;

**Comment by linvi** [comment]
Hello,

>How could I get the lastest Tweetinvi package: "A compressed file that contain Tweetinvi dills"

I would **strongly** suggest that you use nuget to install Tweetinvi so that you have dependencies automatically installed.

Though if you want you can download the DLL at the bottom of the following page: https://github.com/linvi/tweetinvi/releases/tag/1.3.

> That means that is there any journal paper that related to Tweetinvi. We start to submit our research paper, and we want to cite the paper of Tweetinvi.

I have not written any paper specifically about Tweetinvi, so I would suggest you reference this github (https://github.com/linvi/tweetinvi).

Please update this issue when your paper is out, I like reading research on the subject.

Cheers,
Linvi
