### ISSUE TITLE
PublishTweetInReplyTo for tweet received over Stream creates new tweet instead of reply

### ISSUE THREAD

**Issue by photomoose** [linvi/tweetinvi#53]
I am receiving tweets from the User Stream:

            var stream = Stream.CreateUserStream();
            stream.TweetCreatedByAnyoneButMe += OnTweetCreated;
            await stream.StartStreamAsync();

The event handler processes the tweet then attempts to send a reply back to the user:

        private async static void OnTweetCreated(object sender, TweetReceivedEventArgs e)
        {
                // Do something with the tweet

                Tweet.PublishTweetInReplyTo("Thanks for your request!", e.Tweet);
        }

Unfortunately, it would appear that the reply is simply just a new tweet, and is not attached to the original tweet in the timeline.

See attached screenshot showing reply as new tweet rather than actual reply.

![capture](https://cloud.githubusercontent.com/assets/1983638/10324486/d4bae470-6c81-11e5-9aba-af4a719eeb8d.JPG)

**Comment by linvi** [comment]
Hi,

You are encountering an issue due to Twitter REST API changes. [This issue has already been logged](https://github.com/linvi/tweetinvi/issues/25) and based on the reply from the Twitter developer team this feature will change in 0.9.10.x.

The problem is that Twitter now requires a tweet in reply to another one to contain `@username` of the creator of the tweet that you want to reply to. 

With Tweetinvi 0.9.9.x you will need to first get the tweet and add the `@username` to the text of your tweet as demonstrated below:

``` c#
var tweetToReplyTo = Tweet.GetTweet(tweetToReplyToId);
var tweet = Tweet.PublishTweet(string.Format("@{0} my tweet", tweetToReplyTo.CreatedBy.ScreenName),
    new PublishTweetOptionalParameters()
    {
        InReplyToTweet = tweetToReplyTo
    });
```

Please take time to push the developers to get back on these changes by adding some comment to my post on the developer forum.

https://twittercommunity.com/t/reply-to-tweet-does-not-work-anymore-since-a-few-days/52470

Cheers,
Linvi

**Comment by photomoose** [comment]
Hi Linvi,

Thanks for your response. I can confirm your workaround works perfectly.

In some ways, perhaps it's best to have to explicitly put in the @username for the following reasons:

1. This is similar to how it works on the Twitter website.
2. Given the @username part counts towards the 140 length, you'd be able to check the length of your tweet before sending it.

Thanks for the great library.

Tom
