### ISSUE TITLE
Problems using another account

### ISSUE THREAD

**Issue by juanjhb1894** [linvi/tweetinvi#537]
I finally finished my app when I'm trying to use another account the Authentification was perfect but when I'm trying to post tweet it doesn't work and gives me an error to close my app. When I reestart the program it Start with the developer account and works perfectly.

Can you help me?

**Comment by linvi** [comment]
Hello,

First of all could you please mention which version of Tweetinvi you are using?
If you are not using the latest please try to upgrade.

If your problem is still not solved please share the exception raised by your code and, the callstack as well as the code where you exception is being raised.

Thanks

**Comment by juanjhb1894** [comment]
Sorry, I'm late.
I'm using the last version

**Comment by linvi** [comment]
I am not sure you still encounter the problem but you did not provide the exception that is being raised.

Without this I will not be able to help.

**Comment by linvi** [comment]
Closing the issue for now.
