### ISSUE TITLE
tweetinvi how to learn how many more i can follow today

### ISSUE THREAD

**Issue by MonsterMMORPG** [linvi/tweetinvi#637]
Are there anyway to learn how many more person can be followed today?

When will the remaining limit get refreshed or it is dynamic?

**Comment by linvi** [comment]
I am not sure about this. Usually Twitter does not provide exact information on the subject as they use algorithm to detect bots. 

The algorithm is not only checking the number of person you follow but also the frequency of requests...

I would suggest to check/ask the question on twittercommunity.com but as a general rule try to perform the requests regularly across the day instead of running them all at once.
