### ISSUE TITLE
Coordinates doesn't work

### ISSUE THREAD

**Issue by LoriKovari** [linvi/tweetinvi#640]
``` c#
var message = "tweet";
var location= new Coordinates(2.342528, 48.869702);

var publishParameters = new PublishTweetOptionalParameters
                {
                    Coordinates = location,
                };

Tweet.PublishTweet(message, publishParameters);
```
I get the tweet published but doesn't have a location if look on twitter
Please Help, what am I doing wrong?

**Comment by linvi** [comment]
I have tested it. The problem is that the coordinates you are providing is in the middle of the ocean.

You have to select a proper location to make the coordinates work with Twitter.

``` c#
// Example with New York
var location = new Coordinates(40.7127753, -74.0059728);
```

I can suggest you use https://www.gps-coordinates.org to verify your coordinates.

Here is how it looks in Twitter :

![image](https://user-images.githubusercontent.com/6107439/36079552-14c7ff90-0f7c-11e8-897f-913a998b9456.png)

Cheers,
Linvi

**Comment by LoriKovari** [comment]
My fault :p thanks for the Help a really appreciate
