### ISSUE TITLE
User Streams, Site Streams, and Legacy Endpoint Deprecation

### ISSUE THREAD

**Issue by StephenMP** [linvi/tweetinvi#651]
Hey Linvi,

I'm not sure if you saw [this announcement from Twitter](https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html) or not, but looks like the following will be removed on June 19, 2018.

- User Streams
- Site Streams
- GET direct_messages
- GET direct_messages/sent
- GET direct_messages/show
- POST direct_messages/destroy

Check the blog post I linked. Towards the bottom there is a way to sign up for Beta Access to the new APIs. Might be worth checking out to get Tweetinvi ahead of the curve :)

**Comment by linvi** [comment]
Thank you for your input. I did not they were going to be deprecated but the next 2 versions were planned to take care of this.

Planned for version 2.3

- GET direct_messages
- GET direct_messages/sent
- GET direct_messages/show
- POST direct_messages/destroy

Planned for version 2.4

- User Streams
- Site Streams

**Comment by markiemooster** [comment]
Hi Linvi,

I'm concerned that there may be a gap between Twitter switching off User Streams and when TweetInvi supports Twitter's Account Activity API (its replacement).  

Are you able provide an estimate for when the Account Activity API will be supported?  Is this likely to be before 19 June?  If not, do you know of an alternative that could be used in the interim?  

Thanks

**Comment by linvi** [comment]
I am aware of the deadline of 19th of June. I will be working hard to perform the changes required.

Lets imagine that this is not released by then Tweetinvi already has a base implementation for Streams.

[TrackedStream](https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.Streams/TrackedStream.cs)

This `TrackedStream` contains the event `JsonObjectReceived` that sends all the json events that the stream is returning. By analyzing the json information you will be able to extract out any event that you are interested in.

Though please note that 3.0 (formerly 2.2) is in testing at the moment with iOS, Mac, ASP.NET, ASP.NET Core and (iot/ARM) remaining.

So the development of the new features will kick off probably in the next 2 weeks.

Thanks

**Comment by markiemooster** [comment]
Thanks Linvi.  

I've had a quick look at TrackedStream and, forgive me for being a bit dim witted, wondered what URL should I be passing into StartStream()/StartStreamAsync()?  Is this the URL of my web hook or something else?

**Comment by linvi** [comment]
Just as a quick comment. It looks like Twitter is actually migrating away from the streaming to `webhooks`.

So all the logic will have to be done differently for this Account Activity.

**Comment by markiemooster** [comment]
Thanks for your reply.  

If streams won't be suitable and TweetInvi support for Account Activity is not ready by 19th June, is there another alternative?

**Comment by linvi** [comment]
Hi,

I did not have enough time to look carefully at this new api but it looks like the `TwitterAccessor` should be enough to initiate a WebHook request.

Because Twitter is moving to webhooks, your website/service will have to listen to the provided urls.
As a result if you use any Console application or such you will have to open your service to the world and make it publicly available so that Twitter can send the event information to your defined url.

I would suggest your start looking at some articles like this [one](https://www.hanselman.com/blog/IntroducingASPNETWebHooksReceiversWebHooksMadeEasy.aspx) to understand what webhooks are and how to listen to them.

From a Tweetinvi perspective, I will have to see how to properly handle subscription to webhooks to make the life of developers as simple as possible.

By the way if you agree I might request feedback on the implementation here and get some feedback from your vision of it if you feel confident to provide such.

Thanks,
Linvi

**Comment by linvi** [comment]
Tweetinvi 3.0 is now live. Next version will be only on this new Activity Api.

Cheers,
Linvi

**Comment by markiemooster** [comment]
Thanks Linvi.  Will be happy to provide feedback on any changes regarding the Account Activity API.
