### ISSUE TITLE
Wrong TweetLength() with CJK characters

### ISSUE THREAD

**Issue by SDSkyKlouD** [linvi/tweetinvi#679]
First, sorry for my bad English.
I'm working in a simple tweet composer program which uses Tweetinvi as the Twitter API library.
Now I have to get the tweet length before compose it, following calculation mechanism of Twitter's tweet length. So I decided to use `someString.TweetParts().Content.TweetLength()` but I've faced with a problem.
The problem is, you may know, the new tweet length model(Extended Tweet) uses byte length(Alphabets and other Latin characters, e.t.c. are 1 byte per character(0.5 count). CJK characters including Kanji are fixed to 2 bytes(1 count) per character I think), instead of character length.

![20180327_222023](https://user-images.githubusercontent.com/3761972/37970544-b41682b0-320e-11e8-8c9c-7f513a535cba.png)
This shows the difference of length calculation with Korean characters which are counted 1 per character. Top is my program, center text box is from Tweetdeck. The progress bar of my program has Maximum property which was set to 280, and `(textbox.Text).TweetParts().Content.TweetLength()` used as progress bar's value.
As you see, Tweetdeck tells me that the texts are reached its length limit, but my program doesn't.
Not only Korean characters, but also Japanese and Chinese characters.

![20180327_222217](https://user-images.githubusercontent.com/3761972/37970908-9f21012c-320f-11e8-84b9-ddf074165ad6.png)
Same program, same Tweetdeck with English characters(alphabet) which are counted 0.5 per character. Both my program and Tweetdeck tell me that the texts are reached its length limit.

Sorry for my bad explanation... but check about it out please!!

**Comment by linvi** [comment]
Hello,

Please note that Tweetinvi in version 3.0 (which is in testing at the moment) will not support TweetLength.

The reason behind this is that Twitter changed their calculation algorithm and until I have time to properly redevelop this feature to match all the new conditions from Twitter you will have to use their library `twitter-text`. 

It is very simple to use and I will suggest that you use the node.js version inside a micro service.

I know this is not ideal and this decision has been made so that you do not send incorrect information to your clients.

You can find Twitter official length library here : https://github.com/twitter/twitter-text

Thanks,
Linvi

**Comment by linvi** [comment]
I will put back the function as part of the `StringExtensions` but change the name.

DEV NOTE :  Change 3.0 `internal TweetLength` to `public static EstimateTweetLength` and provide additional information as to why this is an estimate.

**Comment by SDSkyKlouD** [comment]
OK then maybe I have to find the way to use `twitter-text` with Node.js within my program... I really appreciate you explaining!

**Comment by linvi** [comment]
Reopening until obsolete restored in 3.0

**Comment by linvi** [comment]
Renamed to `EstimateTweetLength`
