### ISSUE TITLE
Desktop app security

### ISSUE THREAD

**Issue by komBAS** [linvi/tweetinvi#68]
Hi linvi,

I am writing a WinForm desktop application and to create the user credentials I need to use the consumer key and the consumer secret of my twitter app.

Twitter writes: Keep the "Consumer Secret" a secret. This key should never be human-readable in your application.

So far so good, but how do I do this? At least in the moment where I call 

new TwitterCredentials(.....)

in my code the consumer secret is visible in plain form even if it was somehow encrypted before.

Another way I tried was to server the TwitterCredentials via a WCF service on demand, but the TwitterCredentials in tweetinvi don't seem to be serializable - which would be nice btw.

So, do you have any suggestions how to secure my consumer secret in a desktop app or do I see the security problem wrong here? I mean if someone extracts my twitter consumer key and secret my app is captured, right?

Thanks,
Kay

**Comment by linvi** [comment]
Security is always an issue and to point this out, Twitter Private Keys are available online...
Tweetinvi does not provide a secured mechanism as I think it is up to the developer to implement it the way he wants. I would agree that the keys should not be available in plain text in the application.

Here are different advices I could give.
* For security purposes you can encrypt the .dll containing the credentials. 
* If you want to give the credentials through WCF just create your own class with the `DataContract`  attribute. And then build the TwitterCredentials from this.
* Otherwise you can pass through the actions to do to a WCF service.The issue with this is obviously that the operation will now be executed on the server.

If someone capture yours ConsumerKey and ConsumerSecret then they will be able to ask users to authenticate as if they were authenticating from your Application. The attackers would also be able to use the different endpoints requiring Application Only credentials.

**Comment by JoshKeegan** [comment]
Apologies, this is going to get a little off-topic, but my understanding of the Twitter Authentication system is that you each request must be signed with both the Application Secret and the users' Access Token Secret. Because of this, the obvious way to securely make requests from a desktop application that is executed by an untrusted party is to effectively proxy the request via your own server (as you have suggested with a WCF service). Personally, I don't see encrypting the dll as good enough because at some point that dll has to be decrypted for execution, so whilst it adds another hurdle for an attacker to get at your credentials, it's still possible.  
  
Forgive me if I've missed some obvious security pitfall here but I was wondering what your thoughts were on having a signing service for Twitter requests. A server run by a trusted party (probably the developer of the individual application if this were an open source project) could be used to host the Application ID & Secret for any number of Twitter Applications. Then, a desktop client could send its request to the signing service along with the users' Access Token, Secret and the Application ID (which could securely be public information).  
The signing service would then calculate the request signature and return it to the client, without ever having exposed the Application Secret to the user of the desktop application.  
  
The advantage of doing this instead of a proxy would be that the desktop application can make the request to Twitter itself, reducing server load.  
  
The bottom line is that I don't see the need for the Application Secret to be included in the signing key for user requests, and so I don't see why Twitter included it in the first place. Plenty of other APIs allow for clients to connect directly to them provided that the part of the authentication flow to get the bearer token was done by the server (so that the request could be signed with the Application Secret). Having a signing service for Twitter REST API requests would effectively remove the need for you to know the application secret in order to sign a request as a user, which in my opinion makes the process more secure as it removes the temptation for developers to just publish their Application Secret in the code by providing a simple & secure alternative.  
  
I assume you are very familiar with the Twitter Auth process @linvi so your comments would be much appreciated.

**Comment by komBAS** [comment]
Hi JoshKeegan,

MY problem and that was the focus of my initial question is:

The TwitterCredentials object from tweetinvi library contains both, the user tokens and the app tokens.

So if you are familiar with debugging or monitoring an application (I am not an expert) I imagine that someone could spoof these informations. If I am wrong, then I am fine with that.

What I do now to not store the consumer tokens within my desktop app is, I request them from my own WCF service if I need an authetication in my desktop app. So they are still stored unencrypted in the TwitterCredentials object of the library but not in the application itself.

**Comment by JoshKeegan** [comment]
Hi @komBAS,
I think what you're currently doing is option number 2 that @linvi listed, but I'd consider that to be insecure. An attacker could retrieve the credentials out of the applications memory (like you suggest) and I doubt this would be too difficult.   
  
An easy way for you to get an idea of this is to get System Internals Process Explorer, double click on your application running and go to the Strings tab. You could just scroll through the strings until you see anything that looks vaguely like an application secret & you can do this for strings in memory or in the image (exe & dlls). If you were actually trying to get the secret, you'd filter these strings with some simple regex.
  
Even worse, if you fetch the credentials over an unencrypted connection, they would be trivial to intercept by the user of that machine, but also potentially by other users of the same network through packet sniffing (e.g. Wireshark).
  
The standard way of making a request without exposing your Application Secret would be to send the request to your server and then use Tweetinvi on your server to send that request to Twitter. Then the application just returns the results to your desktop application. This is option number 3 that @linvi listed. If you do this, you will have to implement your own authentication for the application to your server, otherwise you'd close one security hole just to open another.  
  
My earlier post was a potential idea for how to avoid proxying these requests, and would also remove the need for authentication between the client & server as that would be contained within the fact that they have the Twitter User Access Token & Secret. For now, you're stuck with proxying if you want security.

**Comment by linvi** [comment]
Thank you Josh,

I think there are 2 ways to make an application totally secured.

* The first way as you mentioned would be to create the WebRequest headers directly in the WCF application and return these to the Application that would then execute the query.

   This solution could be done but I obviously need to do some work in order to provide such a feature. The way to retrieve the Authentication Header could be set up directly in the TweetinviConfig class or something similar. Obviously such a feature will not be implemented before Tweetinvi 1.1 or 1.2 as I want to have all the endpoints covered before adding extra features.

* With the current version of Tweetinvi what you can do instead is to create a Session on your server that will store the `TwitterCredentials`. These credentials will NEVER be available within the client. Instead during the authentication mechanism you will provide the required information to the service in order for the process to succeed. After that the server will store these credentials and execute the queries directly. Obviously if you have thousands of user you will need to consider the charge of having a server executing thousands of queries.

Thank you Josh for your insight they were quite valuable and I will consider adding a way to have a WebRequest signing server side.

Cheers,
Linvi

**Comment by JoshKeegan** [comment]
Thanks Linvi!
I completely agree that Tweetinvi should cover all of the endpoints before adding any extra features like this which are really above and beyond what you'd expect from a library like this.

**Comment by linvi** [comment]
Good news for this 1+ years old post! #220 will now allow developers to build an object that contains all the information required for the developer to execute from another client!

By doing so you no longer have to expose your credentials in the client that execute the HttpRequest.
The server can now sign a request that the client can then execute.

I hope this will solve anyone problem.
