### ISSUE TITLE
Question on location object

### ISSUE THREAD

**Issue by manastalukdar** [linvi/tweetinvi#72]
What do the two ICoordinates arguments for the constructor really imply? I am looking to use the latitude and longitude based on the user clicking a certain location on a map, and was hoping to get the Location from it, but the double coordinates for Location is creating some confusion. Could the developer please shed some light on the Location object?

**Comment by linvi** [comment]
Hello I understand that this can be misleading. The reason I called this `Location` instead of `BoundingBox` is the fact that Twitter uses location in their [documentation](https://dev.twitter.com/streaming/reference/post/statuses/filter).

`Coordinates` refers to a very specific point and they are used for example when you want to publish a `Tweet`.

`Location` is a set of 2 `Coordinates` that create a rectangular box. `FilteredStream` for example uses a Location to receive all the Tweets that are published from a specific area on the planet.

C1
 x-----------------------
 |                             |
 |                             |
 |----------------------x
                             C2

Please let me know if this makes sense.
Cheers,
Linvi

**Comment by manastalukdar** [comment]
Thanks, that answers my question.
