### ISSUE TITLE
most popular tweets in a topic 

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#731]
Hello, ı use the following code : `SearchType = SearchResultType.Popular ,MaximumNumberOfResults = 1,`
and search tweets with a topic. I actually want to see what is the most retweeted tweet about this topic, but i get second most retweeted tweet. how can i solve this problem ? thanks

**Comment by linvi** [comment]
I am not sure what you want exactly but keep in mind that Search is not something that Twitter consider sending the exact result to your request because of multiple reasons.

Anyway, Tweetinvi is returning exactly what Twitter returns from their API. If the result is not what you wish, I would suggest to increase the number of results and use your own filters in your code.
