### ISSUE TITLE
search excluding replies

### ISSUE THREAD

**Issue by ghentsch** [linvi/tweetinvi#788]
Is there a way to exclude replies from a search? In the past (pre-tweetinvi), i'd use "from:anaccount exclude:replies" or "from:anaccount -filter:replies".

**Comment by JoshKeegan** [comment]
Any of the standard boolean search operators will still work within Tweetinvi (they're applied by Twitter's API, so Tweetinvi will just pass your request on).  

Additional filters are also available in `SearchTweetsParameters` (see [the wiki](https://github.com/linvi/tweetinvi/wiki/Searches) for usage). Off of the top of my head, I don't think there is one for everything but replies though, so your existing boolean search is probably the way to go.

**Comment by ghentsch** [comment]
Sadly, stuffing the exclude parameter in the search string prior to tweetinvi appending other parameters doesn't work (at least some of the time likely due to twitter's ordering of parameters weirdness). It might be a good addition to SearchTweetsParameters to have an exclude parameter for replies, images,.. Although there is no docs about exclude in the twitter docs but perhaps -filter:replies would work because -filter appears documented.

**Comment by JoshKeegan** [comment]
Have you tried running the undocumented boolean search directly against the API yourself (not via Tweetinvi) since the premium APIs were introduced?

**Comment by ghentsch** [comment]
I haven't tried the -filter searches but use the following for excluding retweets and replies.

-RT%20from%3A@bannisterlake%20exclude%3Areplies

**Comment by linvi** [comment]
@ghentsch I would suggest you check these 2 pages : 

## https://twitter.com/search-advanced

By filling the fields there you will find how to build the query by checking the generated URL.

For example: 

**None of these words** : hello

Generates the url : https://twitter.com/search?l=&q=-hello&src=typd

Where you can see the `q=-hello`.

## https://twitter.com/search-home

There are various operators that are explained on the page :

Operator | Finds tweets...
-- | --
twitter search | containing both "twitter" and "search". This is the default operator.
"happy hour" | containing the exact phrase "happy hour".
love OR hate | containing either "love" or "hate" (or both).
beer -root | containing "beer" but not "root".
#haiku | containing the hashtag "haiku".
from:alexiskold | sent from person "alexiskold".
to:techcrunch | sent to person "techcrunch".
@mashable | referencing person "mashable".
"happy hour" near:"san francisco" | containing the exact phrase "happy hour" and sent near "san francisco".
near:NYC within:15mi | sent within 15 miles of "NYC".
superhero since:2010-12-27 | containing "superhero" and sent since date "2010-12-27" (year-month-day).
ftw until:2010-12-27 | containing "ftw" and sent up to date "2010-12-27".
hilarious filter:links | containing "hilarious" and linking to URLs.
news source:"Twitter Lite" | containing "news" and entered via Twitter Lite

**Comment by linvi** [comment]
Todo add these information in the Search documentation page.
