### ISSUE TITLE
PublishTweetWithMedia fails with code 186 (>140 chars)

### ISSUE THREAD

**Issue by gsogol** [linvi/tweetinvi#86]
I use the following api:
<code>
await Tweetinvi.TwitterCredentials.ExecuteOperationWithCredentials(credentials, async () =>
                {
                    await TweetAsync.PublishTweetWithMedia("How Real Estate Agents Get More Closings By Using SMS Text Messaging - DialMyCalls.com http://bit.ly/1kmezw9", image);
                });
</code>

The image are the bytes from https://www.dialmycalls.com/img/dmc-logo-fbmain.png url which is about 22kb. The text is 108 characters.

Why does twitter say I'm more than 140 characters?

**Comment by linvi** [comment]
Tweetinvi works correctly, adding an image to a Tweet usually adds 24 characters to this message. Your text with the URL that you gave is of 118 characters, meaning you have 22 left.

Therefore if you want to add an image, you will have a message of 142 characters.

In the meantime there is a bug in Tweetinvi because if you use `Tweet.Length()` it will return a size of 139 which is incorrect. I will fix this issue.

Cheers,
Linvi

**Comment by gsogol** [comment]
I see. Thanks.
