### ISSUE TITLE
How do you pause/stop a filtered stream

### ISSUE THREAD

**Issue by tastyPainkillers** [linvi/tweetinvi#981]
ive written some multi threading code that detects the esc key being pressed while the stream is running so eventually i can use that to pause the stream. But when the program just sits on the stream.MatchingTweetReceived += (sender, args) => line until it finds another tweet to deal with. i cant find any way to stop or pause the stream when it is in this searching for tweet state and was wondering if there is actually a way to do it or do i have to cut it off once its found one to deal with, because it would be very inconvenient if that was the case.
![Capture](https://user-images.githubusercontent.com/61563110/75486403-5c85c280-59a4-11ea-9237-321a8b014bc6.PNG)

**Comment by jdahan91** [comment]
Computer programs execute in a linear way, which means that after the "if" statement is compared it will never run again. Why aren't you just using a string or better yet a bool type instead of boxing a string into an object?

Anyways what I would refactor is by putting the "if" statement last line and right before it a Console.ReadKey to pause execution and wait for input (better than polling inside a thread).

**Comment by tastyPainkillers** [comment]
I managed to fix it by using startStreamMatchingAllConditionsAsync() at the end of the block of code and dealing with the result of the multi threading down there. Thanks for the reply though

**Comment by jdahan91** [comment]
> I managed to fix it by using startStreamMatchingAllConditionsAsync() at the end of the block of code and dealing with the result of the multi threading down there. Thanks for the reply though

Yes, that call is synchronous which means it will block the calling thread.
